spring.datasource:
  url: jdbc:h2:mem:micro-member;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL
  username: sa

spring.jpa:
    database: mysql
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hbm2ddl: update

spring.h2.console:
      enabled: true

